Increase recovery.img size
increased because i was getting the error

error: /home/winterr/android/FloppyCM/out/target/product/p700/recovery.img too large (9056256 > [8650752 - 270336])